### ISSUE TITLE
"counter" that shows current image-index and total index

### ISSUE THREAD

**Issue by gibbswe** [rstacruz/swipeshow#30]
Trying to figure out how to use "onactivate" to update an element with the current index-number and also fetch the total index. Is this possible or do you need to add something to the code?

Like:
onactivate: function() {
   document.getElementById("slide-counter").innerHTML = index + " / " + index_total;
}

**Comment by rstacruz** [comment]
> The onactivate hook is called when you first initialize swipeshow, and again each time a swipe event occurs. The method receives the following arguments:
>
> *  current slide (DOM object)
> *  current slide index
> *  previous slide (DOM object)
> *  previous slide index

that is:

there's no way to get the total though, but you can probably get away with counting `.slide`'s.
```js
onactivate: function (current, i, previous, j) {
  var total = $(current).closest('.slides').find('.slide').length;
  $("slide-counter").html("" + i + "/" + total);
}
```

**Comment by gibbswe** [comment]
Thanks man, worked great!
