### ISSUE TITLE
Automatic height

### ISSUE THREAD

**Issue by o-l-e** [rstacruz/swipeshow#4]
Hi, and compliments on a nice simple slider.

I am trying to make the slider responsive, with variable sized content.
Everything works well, but the height is really tricky.
Is it possible to somehow "make the slider the height of tallest image"?
It seems the slider needs a set height in the css, which is a bit tricky when the width (also css) is set to for example 100%.

Hope you understand the question :)

**Comment by OneMohrTime** [comment]
@o-l-e I was just recently able to **finally** overcome this by assinging 'height' to 'auto', and then assigning psuedo elements to maintain a certain aspect ratio.

You can find the (hack?) on CSS Tricks, plus LESS/SCSS mixins.
https://css-tricks.com/snippets/sass/maintain-aspect-ratio-mixin/

Let me know if this worked for you, hoping it wasn't just a fluke of some other element I have mixed in.

**Comment by o-l-e** [comment]
Sorry @OneMohrTime i didn't end up pursuing this any further, so i ended up using another slider. But thanks so much for your input, and hope somebody else finds it useful :)
