### ISSUE TITLE
Make it Responsive

### ISSUE THREAD

**Issue by rahulpatwa** [rstacruz/swipeshow#7]
Currently you need to give the slideshow div container height and width in pixels..If given in % then the slides do not show. 
If you fix this issue then it can be used responsively. :)

**Comment by OneMohrTime** [comment]
@rahulpatwa I was just recently able to **finally** overcome this by assinging 'height' to 'auto', and then assigning psuedo elements to maintain a certain aspect ratio.

You can find the (hack?) on CSS Tricks, plus LESS/SCSS mixins.
https://css-tricks.com/snippets/sass/maintain-aspect-ratio-mixin/

Let me know if this worked for you, hoping it wasn't just a fluke of some other element I have mixed in.
